"""add_metrics_tables

Revision ID: 2becf6dc8b9f
Revises: a1b2c3d4e5f6
Create Date: 2026-07-19 23:22:19.045702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2becf6dc8b9f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('default_upper_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('default_lower_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_dict_code'), 'indicator_dict', ['code'], unique=True)
    op.create_table('indicator_version_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_item_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_item_collection_code'), 'test_item_collection', ['code'], unique=True)
    op.create_table('bom_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_code', sa.String(length=100), nullable=False),
    sa.Column('bom_name', sa.String(length=200), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['test_item_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_config_bom_code'), 'bom_config', ['bom_code'], unique=False)
    op.create_table('collection_test_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['test_item_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_config_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('upper_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('lower_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('judgment_rule', sa.String(length=20), nullable=False),
    sa.Column('test_stage', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bom_config_id'], ['bom_config.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_sub_scenario_id'), 'test_runs', ['sub_scenario_id'], unique=False)
    op.create_index(op.f('ix_test_runs_version_id'), 'test_runs', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_runs_version_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_sub_scenario_id'), table_name='test_runs')
    op.drop_table('bom_indicator')
    op.drop_table('collection_test_item')
    op.drop_index(op.f('ix_bom_config_bom_code'), table_name='bom_config')
    op.drop_table('bom_config')
    op.drop_index(op.f('ix_test_item_collection_code'), table_name='test_item_collection')
    op.drop_table('test_item_collection')
    op.drop_table('indicator_version_snapshot')
    op.drop_index(op.f('ix_indicator_dict_code'), table_name='indicator_dict')
    op.drop_table('indicator_dict')
    # ### end Alembic commands ###
