"""add_test_logs

Revision ID: 47712bb2651e
Revises: 9ac297f9e3c3
Create Date: 2026-07-12 16:43:28.190676
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47712bb2651e'
down_revision: Union[str, None] = '9ac297f9e3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_logs_created_at'), 'test_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_logs_run_id'), 'test_logs', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_logs_run_id'), table_name='test_logs')
    op.drop_index(op.f('ix_test_logs_created_at'), table_name='test_logs')
    op.drop_table('test_logs')
    # ### end Alembic commands ###
