"""initial_schema

Revision ID: 9ac297f9e3c3
Revises: 
Create Date: 2026-07-12 16:38:52.169479
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac297f9e3c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_version', sa.String(length=20), nullable=False),
    sa.Column('default_equipment_config', sa.JSON(), nullable=True),
    sa.Column('default_hardware_params', sa.JSON(), nullable=True),
    sa.Column('default_software_config', sa.JSON(), nullable=True),
    sa.Column('default_scenario_config', sa.JSON(), nullable=True),
    sa.Column('layout_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_equipment_definitions_name'), 'equipment_definitions', ['name'], unique=True)
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_factories_name'), 'factories', ['name'], unique=True)
    op.create_table('test_item_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_address', sa.String(length=500), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_item_templates_category'), 'test_item_templates', ['category'], unique=False)
    op.create_index(op.f('ix_test_item_templates_name'), 'test_item_templates', ['name'], unique=False)
    op.create_table('test_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_items_category'), 'test_items', ['category'], unique=False)
    op.create_index(op.f('ix_test_items_name'), 'test_items', ['name'], unique=False)
    op.create_table('test_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sequences_name'), 'test_sequences', ['name'], unique=False)
    op.create_table('test_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.String(length=200), nullable=False),
    sa.Column('workstation', sa.String(length=200), nullable=False),
    sa.Column('codes_config', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('bom_code', sa.String(length=200), nullable=False),
    sa.Column('tps_name', sa.String(length=200), nullable=False),
    sa.Column('domain_tags', sa.String(length=500), nullable=False),
    sa.Column('inherit_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inherit_from_id'], ['test_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_versions_project_name'), 'test_versions', ['project_name'], unique=False)
    op.create_index(op.f('ix_test_versions_status'), 'test_versions', ['status'], unique=False)
    op.create_index(op.f('ix_test_versions_version'), 'test_versions', ['version'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_factory_id'), 'production_lines', ['factory_id'], unique=False)
    op.create_table('release_deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('factory_name', sa.String(length=200), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('line_name', sa.String(length=200), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['test_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_deployments_version_id'), 'release_deployments', ['version_id'], unique=False)
    op.create_table('release_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('approver_role', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['test_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_steps_version_id'), 'release_steps', ['version_id'], unique=False)
    op.create_table('sub_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.String(length=100), nullable=False),
    sa.Column('workstation', sa.String(length=100), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('hardware_params', sa.JSON(), nullable=True),
    sa.Column('software_metrics', sa.JSON(), nullable=True),
    sa.Column('property_page', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['test_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_scenarios_version_id'), 'sub_scenarios', ['version_id'], unique=False)
    op.create_table('test_sequence_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['test_sequences.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['test_item_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sequence_steps_sequence_id'), 'test_sequence_steps', ['sequence_id'], unique=False)
    op.create_table('version_archive_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['test_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_archive_items_version_id'), 'version_archive_items', ['version_id'], unique=False)
    op.create_table('version_binary_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['test_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_binary_files_version_id'), 'version_binary_files', ['version_id'], unique=False)
    op.create_table('test_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('definition_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deployed_version', sa.String(length=20), nullable=False),
    sa.Column('latest_version', sa.String(length=20), nullable=False),
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('workstation', sa.String(length=50), nullable=False),
    sa.Column('actuator', sa.String(length=100), nullable=False),
    sa.Column('hardware_code', sa.String(length=100), nullable=False),
    sa.Column('software_code', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('has_settings', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['equipment_definitions.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_stations_definition_id'), 'test_stations', ['definition_id'], unique=False)
    op.create_index(op.f('ix_test_stations_line_id'), 'test_stations', ['line_id'], unique=False)
    op.create_index(op.f('ix_test_stations_name'), 'test_stations', ['name'], unique=True)
    op.create_table('cabinets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinets_station_id'), 'cabinets', ['station_id'], unique=False)
    op.create_table('equipment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('auto_load_enabled', sa.Boolean(), nullable=False),
    sa.Column('debug_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('equipment_ip', sa.String(length=50), nullable=False),
    sa.Column('equipment_service_address', sa.String(length=200), nullable=False),
    sa.Column('process_control_enabled', sa.Boolean(), nullable=False),
    sa.Column('test_mode_normal', sa.Boolean(), nullable=False),
    sa.Column('test_mode_verify', sa.Boolean(), nullable=False),
    sa.Column('test_mode_calibration', sa.Boolean(), nullable=False),
    sa.Column('barcode_verify_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id')
    )
    op.create_table('equipment_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id')
    )
    op.create_table('equipment_property_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('page_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id')
    )
    op.create_table('hardware_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(length=200), nullable=False),
    sa.Column('param_value', sa.String(length=500), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_params_station_id'), 'hardware_params', ['station_id'], unique=False)
    op.create_table('scenario_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('scenario_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id')
    )
    op.create_table('software_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('dut_version', sa.String(length=100), nullable=False),
    sa.Column('dut_firmware_version', sa.String(length=100), nullable=False),
    sa.Column('dut_hardware_version', sa.String(length=100), nullable=False),
    sa.Column('selected_test_item_ids', sa.JSON(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('sequence_data', sa.JSON(), nullable=True),
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('workstation', sa.String(length=50), nullable=False),
    sa.Column('selected_code', sa.String(length=100), nullable=False),
    sa.Column('bom_code', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_chassis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_chassis_cabinet_id'), 'test_chassis', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_test_chassis_station_id'), 'test_chassis', ['station_id'], unique=False)
    op.create_table('test_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chassis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_batch_id', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chassis_id'], ['test_chassis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_slots_chassis_id'), 'test_slots', ['chassis_id'], unique=False)
    op.create_index(op.f('ix_test_slots_status'), 'test_slots', ['status'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('task_order', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('passed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('sequence_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['test_slots.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['test_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_batch_id'), 'test_runs', ['batch_id'], unique=True)
    op.create_index(op.f('ix_test_runs_created_at'), 'test_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_runs_operator'), 'test_runs', ['operator'], unique=False)
    op.create_index(op.f('ix_test_runs_serial_number'), 'test_runs', ['serial_number'], unique=False)
    op.create_index(op.f('ix_test_runs_slot_id'), 'test_runs', ['slot_id'], unique=False)
    op.create_index(op.f('ix_test_runs_station_id'), 'test_runs', ['station_id'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_runs_task_order'), 'test_runs', ['task_order'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_item_id', sa.Integer(), nullable=False),
    sa.Column('test_run_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('tested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_item_id'], ['test_items.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_operator'), 'test_results', ['operator'], unique=False)
    op.create_index(op.f('ix_test_results_serial_number'), 'test_results', ['serial_number'], unique=False)
    op.create_index(op.f('ix_test_results_test_item_id'), 'test_results', ['test_item_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_test_results_tested_at'), 'test_results', ['tested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_tested_at'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_item_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_serial_number'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_operator'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_runs_task_order'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_station_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_slot_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_serial_number'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_operator'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_created_at'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_batch_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_test_slots_status'), table_name='test_slots')
    op.drop_index(op.f('ix_test_slots_chassis_id'), table_name='test_slots')
    op.drop_table('test_slots')
    op.drop_index(op.f('ix_test_chassis_station_id'), table_name='test_chassis')
    op.drop_index(op.f('ix_test_chassis_cabinet_id'), table_name='test_chassis')
    op.drop_table('test_chassis')
    op.drop_table('software_configs')
    op.drop_table('scenario_configs')
    op.drop_index(op.f('ix_hardware_params_station_id'), table_name='hardware_params')
    op.drop_table('hardware_params')
    op.drop_table('equipment_property_pages')
    op.drop_table('equipment_metrics')
    op.drop_table('equipment_configs')
    op.drop_index(op.f('ix_cabinets_station_id'), table_name='cabinets')
    op.drop_table('cabinets')
    op.drop_index(op.f('ix_test_stations_name'), table_name='test_stations')
    op.drop_index(op.f('ix_test_stations_line_id'), table_name='test_stations')
    op.drop_index(op.f('ix_test_stations_definition_id'), table_name='test_stations')
    op.drop_table('test_stations')
    op.drop_index(op.f('ix_version_binary_files_version_id'), table_name='version_binary_files')
    op.drop_table('version_binary_files')
    op.drop_index(op.f('ix_version_archive_items_version_id'), table_name='version_archive_items')
    op.drop_table('version_archive_items')
    op.drop_index(op.f('ix_test_sequence_steps_sequence_id'), table_name='test_sequence_steps')
    op.drop_table('test_sequence_steps')
    op.drop_index(op.f('ix_sub_scenarios_version_id'), table_name='sub_scenarios')
    op.drop_table('sub_scenarios')
    op.drop_index(op.f('ix_release_steps_version_id'), table_name='release_steps')
    op.drop_table('release_steps')
    op.drop_index(op.f('ix_release_deployments_version_id'), table_name='release_deployments')
    op.drop_table('release_deployments')
    op.drop_index(op.f('ix_production_lines_factory_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_versions_version'), table_name='test_versions')
    op.drop_index(op.f('ix_test_versions_status'), table_name='test_versions')
    op.drop_index(op.f('ix_test_versions_project_name'), table_name='test_versions')
    op.drop_table('test_versions')
    op.drop_index(op.f('ix_test_sequences_name'), table_name='test_sequences')
    op.drop_table('test_sequences')
    op.drop_index(op.f('ix_test_items_name'), table_name='test_items')
    op.drop_index(op.f('ix_test_items_category'), table_name='test_items')
    op.drop_table('test_items')
    op.drop_index(op.f('ix_test_item_templates_name'), table_name='test_item_templates')
    op.drop_index(op.f('ix_test_item_templates_category'), table_name='test_item_templates')
    op.drop_table('test_item_templates')
    op.drop_index(op.f('ix_factories_name'), table_name='factories')
    op.drop_table('factories')
    op.drop_index(op.f('ix_equipment_definitions_name'), table_name='equipment_definitions')
    op.drop_table('equipment_definitions')
    # ### end Alembic commands ###
