"""unify_indicator_params

Revision ID: b8e3c2d1a4f5
Revises: 1a8d34795881
Create Date: 2026-07-24 20:30:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8e3c2d1a4f5'
down_revision: Union[str, None] = '1a8d34795881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add new unified columns to indicator_dict
    op.add_column('indicator_dict', sa.Column('hardware_model', sa.String(length=100), nullable=True))
    op.add_column('indicator_dict', sa.Column('test_rule', sa.Text(), nullable=True))
    op.add_column('indicator_dict', sa.Column('params', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('indicator_dict', sa.Column('remark', sa.Text(), nullable=True))

    # 2. Migrate old independent threshold columns into JSON params
    indicator_dict = table(
        'indicator_dict',
        column('id', sa.Integer),
        column('default_upper_limit', sa.Numeric),
        column('default_lower_limit', sa.Numeric),
        column('params', sa.JSON),
    )
    op.execute(
        indicator_dict.update().values(
            params=sa.case(
                (
                    sa.or_(
                        indicator_dict.c.default_upper_limit.isnot(None),
                        indicator_dict.c.default_lower_limit.isnot(None),
                    ),
                    sa.func.json_object(
                        'format_type', 'number',
                        'upper_limit', sa.func.coalesce(indicator_dict.c.default_upper_limit, sa.null()),
                        'lower_limit', sa.func.coalesce(indicator_dict.c.default_lower_limit, sa.null()),
                        'standard_value', sa.null(),
                        'precision', sa.null(),
                        'tolerance', sa.null(),
                        'hardware_channel', '',
                        'test_frequency', 1,
                        'exceed_handler', 'ALARM',
                        'extend_params', sa.cast('[]', sa.JSON),
                    )
                ),
                else_='{}'
            )
        )
    )

    # 3. Drop old columns from indicator_dict
    op.drop_column('indicator_dict', 'default_upper_limit')
    op.drop_column('indicator_dict', 'default_lower_limit')
    op.drop_column('indicator_dict', 'alarm_level')
    op.drop_column('indicator_dict', 'python_script')

    # 4. Drop old threshold columns from bom_indicator
    op.drop_column('bom_indicator', 'upper_limit')
    op.drop_column('bom_indicator', 'lower_limit')

    # 5. Drop old threshold columns from test_item_indicator
    op.drop_column('test_item_indicator', 'upper_limit')
    op.drop_column('test_item_indicator', 'lower_limit')

    # 6. Drop obsolete bom_indicator_param table
    op.drop_table('bom_indicator_param')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Recreate bom_indicator_param table
    op.create_table('bom_indicator_param',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bom_indicator_id', sa.Integer(), nullable=False),
        sa.Column('param_key', sa.String(length=80), nullable=False),
        sa.Column('param_name', sa.String(length=100), nullable=True),
        sa.Column('param_value', sa.String(length=500), nullable=True),
        sa.Column('param_type', sa.String(length=20), nullable=True),
        sa.Column('remark', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['bom_indicator_id'], ['bom_indicator.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. Add back old threshold columns
    op.add_column('test_item_indicator', sa.Column('upper_limit', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('test_item_indicator', sa.Column('lower_limit', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('bom_indicator', sa.Column('upper_limit', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('bom_indicator', sa.Column('lower_limit', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('indicator_dict', sa.Column('python_script', sa.Text(), nullable=True))
    op.add_column('indicator_dict', sa.Column('alarm_level', sa.String(length=20), nullable=True))
    op.add_column('indicator_dict', sa.Column('default_upper_limit', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('indicator_dict', sa.Column('default_lower_limit', sa.Numeric(precision=12, scale=4), nullable=True))

    # 3. Drop new unified columns
    op.drop_column('indicator_dict', 'remark')
    op.drop_column('indicator_dict', 'params')
    op.drop_column('indicator_dict', 'test_rule')
    op.drop_column('indicator_dict', 'hardware_model')

    # ### end Alembic commands ###
